#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Note when testing Python 3, the 'python' command will invoke Python 3
#and similarly for PyPy too.

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

#This should enable the container-based Travis CI infrastructure
#(faster startup, caches public repos, but cannot use sudo):
sudo: false

#Install apt packages under container-based Travis CI infrastructure
#avoiding "sudo apt-get install ..." - see http://docs.travis-ci.com/user/apt/
addons:
  apt:
    packages:
    - clustalw
    - clustalo
    - muscle
    - mafft
    - probcons
    - wise
    - emboss
    - samtools
    - bwa

before_install:
  - "export PY3=yes"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then export PY3=no; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export PY3=no; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then export PY3=no; fi"
  - "export PYPY=no"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then export PYPY=yes; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then export PYPY=yes; fi"
##Suspect an update of t-coffee is causing the test run to stall...
##  - "apt-get install --no-install-recommends t-coffee"
#Misc python modules we can use as soft dependencies
  - "if [[ $PYPY != 'yes' ]]; then pip install reportlab; fi"
  - "pip install rdflib"
#Not hosted on PyPI so this need allow external switch:
#Currently pypy3-2.4.0 self reports as Python 3.2,
#which is not supported by mysql-connector-python
  - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy3' ]]; then pip install --allow-all-external mysql-connector-python; fi"
#Installing psycopg2 does not work under PyPy or Jython
  - "export PG=yes"
  - "if [[ $PYPY == 'yes' ]]; then export PG=no; fi"
  - "if [[ $PG == 'yes' ]]; then pip install psycopg2 --use-mirrors; fi"
#Installing mysql-python does not work under Python 3
  - "export MSQL=$PG"
  - "if [[ $PY3 == 'yes' ]]; then export MSQL=no; fi"
  - "if [[ $MSQL == 'yes' ]]; then pip install mysql-python --use-mirrors; fi"

install:
  - "/usr/bin/yes | python setup.py install"

before_script:
  - cd Tests

script:
  - python run_tests.py --offline

#The email defaults are too talkative while we're getting Travis working nicely.
notifications:
  email: false
