#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Note when testing Python 3, the 'python' command will invoke Python 3
#(which we now do via $PYTHON_EXE).

language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

before_install:
  - "sudo apt-get install clustalw clustalo | tail -n 2"
  - "sudo apt-get install t-coffee muscle mafft probcons wise emboss 2>&1 | tail -n 2"
#Installing psycopg2 does not work under PyPy or Jython
  - "export PG=yes"
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then export PG=no; fi"
  - "if [[ $PG == 'yes' ]]; then pip install psycopg2 --use-mirrors 2>&1 | tail -n 2; fi"
#Installing mysql-python does not work under Python 3.2
  - "export MSQL=$PG"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then export MSQL=no; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then export MSQL=no; fi"
  - "if [[ $MSQL == 'yes' ]]; then pip install mysql-python --use-mirrors 2>&1 | tail -n 2; fi"

install:
#Recently TravisCI builds have been failing with a path problem of some kind,
  - pwd
  - ls -l
  - "/usr/bin/yes | $PYTHON_EXE setup.py install 2>&1 | tail -n 2"

before_script:
  - cd Tests
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then cd ../build/py3.2/Tests; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then cd ../build/py3.3/Tests; fi"

script:
  - $PYTHON_EXE run_tests.py --offline

#The email defaults are too talkative while we're getting Travis working nicely.
notifications:
  email: false
